# Generated by Django 2.0 on 2019-03-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='邀请码')),
                ('valid', models.CharField(blank=True, default='yes', max_length=32, verbose_name='是否有效')),
                ('invalid_date', models.DateTimeField(auto_now=True, verbose_name='失效时间')),
            ],
        ),
    ]
