# Generated by Django 2.0 on 2019-03-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationcode',
            options={'verbose_name': '邀请码'},
        ),
    ]
