# Generated by Django 2.0 on 2019-03-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190321_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usage_count',
            field=models.IntegerField(default=500, max_length=128, verbose_name='可使用次数'),
        ),
    ]
